// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  expect = chai.expect;

  describe('Spec on library presentations', function() {
    var $presentation_list, $temp, library;
    library = null;
    $temp = null;
    $presentation_list = [];
    before(function() {
      return $(document.body).append($temp = $('<div>'));
    });
    beforeEach(function() {
      $presentation_list = [new Presentation('Первая презентация', ['http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-1-638.jpg?cb=1386772521', 'http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-2-1024.jpg?cb=1386772521', 'http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-6-1024.jpg?cb=1386772521']), new Presentation('Вторая презентация', ['http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-6-1024.jpg?cb=1386772521', 'http://image.slidesharecdn.com/howtobuildamvpappasanon-techfounder-1-131205164335-phpapp02/95/slide-3-1024.jpg?cb=1386771939', 'http://image.slidesharecdn.com/howtobuildamvpappasanon-techfounder-1-131205164335-phpapp02/95/slide-9-1024.jpg?cb=1386771939']), new Presentation('Третья')];
      return library = new Library($temp, $presentation_list);
    });
    it('should set sequence init', function() {
      var i, _, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = $presentation_list.length; _i < _len; i = ++_i) {
        _ = $presentation_list[i];
        _results.push(expect(_._id).to.eq(i));
      }
      return _results;
    });
    it('get presentation by id', function() {
      return expect(library.get(1)).to.eq($presentation_list[1]);
    });
    describe('render', function() {
      beforeEach(function() {
        return library.render();
      });
      it('should render library in container', function() {
        return expect($temp.find('.presentation').length).to.eq(3);
      });
      it('should set title presentation', function() {
        return expect($temp.find('.presentation h4').eq(1).text()).to.eq('Вторая презентация');
      });
      it('should set img cover for presentation', function() {
        return expect($temp.find('.presentation img').eq(1).attr('src')).to.eq('http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-6-1024.jpg?cb=1386772521');
      });
      return it('should set count slides in presentation', function() {
        return expect($temp.find('.presentation .count-slides').eq(1).text()).to.eq('Слайдов: 3');
      });
    });
    describe('switch slides', function() {
      var present;
      present = null;
      beforeEach(function() {
        return present = library.get(0);
      });
      it('should get current slide', function() {
        var slide;
        slide = present.getCurentSlide();
        return expect(slide).to.eqls({
          index: 1,
          img: 'http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-1-638.jpg?cb=1386772521'
        });
      });
      return it('should swith on next slide', function() {
        present.next().next().next().next();
        return expect(present.getCurentSlide()).to.eqls({
          index: 3,
          img: 'http://image.slidesharecdn.com/10eventtrendsfor2014-131210093316-phpapp01/95/slide-6-1024.jpg?cb=1386772521'
        });
      });
    });
    return after(function() {
      return $temp.remove();
    });
  });

  describe('Spec on presentations', function() {
    return it('should set id ', function() {
      var presentation;
      presentation = new Presentation;
      presentation.setId(2);
      return expect(presentation._id).to.eq(2);
    });
  });

}).call(this);
