// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  expect = chai.expect;

  describe('Spec serialize params and extend with url', function() {
    it('should make simple url', function() {
      var params, url;
      url = 'http://ya.ru/index.html';
      params = {
        test: 1,
        name: 'lol'
      };
      return expect(extendUrlByParams(url, params)).to.eq('http://ya.ru/index.html?test=1&name=lol');
    });
    return it('should with extend params from query', function() {
      var params, url;
      url = 'http://ya.ru/index.html?old_value=test';
      params = {
        test: 1,
        name: 'lol'
      };
      return expect(extendUrlByParams(url, params)).to.eq('http://ya.ru/index.html?old_value=test&test=1&name=lol');
    });
  });

}).call(this);
