// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  expect = chai.expect;

  describe('Spec on compare forms', function() {
    var form1, form2;
    form1 = null;
    form2 = null;
    beforeEach(function() {
      form1 = $(" \n<form>\n  <input type=text name=\"param1\" value=\"test\">\n</form> ");
      return form2 = $(" \n<form>\n  <input type=text name=\"param1\" value=\"test\">\n</form> ");
    });
    it('should answer to equal forms', function() {
      return expect(compareForms(form1, form2)).to.eq('Формы идентичны');
    });
    it('should answer about update param', function() {
      form2.find('[name=param1]').val('new_val');
      return expect(compareForms(form1, form2)).to.eqls(["Обновился парамметр 'param1': был 'test', а стал 'new_val'"]);
    });
    it('should answer delete params', function() {
      form1.append("<input name=arguments  value='test' />").append("<input name=arguments2  value='test' />");
      return expect(compareForms(form1, form2)).to.eqls(["Удалён парамметр 'arguments'", "Удалён парамметр 'arguments2'"]);
    });
    return it('should answer insert params', function() {
      form2.append("<input name=arguments  value='test' />");
      return expect(compareForms(form1, form2)).to.eqls(["Добавлен новый парамметр: 'arguments'"]);
    });
  });

}).call(this);
