// Generated by CoffeeScript 1.6.3
/*
  Преобразование query строки в Object
*/


(function() {
  var arrayParams, getQuery;

  arrayParams = /(.*)\[(.*)\]/;

  window.parseQuery = function(url) {
    var $res, queryStr;
    queryStr = getQuery.apply(null, url.split('?'));
    $res = {};
    if (queryStr != null) {
      queryStr.split('&').forEach(function(item) {
        var key, value, _, _ref;
        _ref = item.split('='), key = _ref[0], value = _ref[1];
        if (_ = key.match(arrayParams)) {
          if (_[2] === "") {
            key = _[1];
            if (!($res[key] instanceof Array)) {
              $res[key] = [];
            }
            return $res[key].push(value);
          } else {
            key = _[1];
            if (typeof $res[key] !== 'object') {
              $res[key] = {};
            }
            return $res[key][_[2]] = value;
          }
        } else {
          return $res[key] = value;
        }
      });
    }
    return $res;
  };

  getQuery = function() {
    var item, _i, _len;
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      item = arguments[_i];
      if (item.match("=|&")) {
        return item;
      }
    }
  };

}).call(this);
