// Generated by CoffeeScript 1.6.3
/*
  Функция сравнения параметров двух форм
*/


(function() {
  var addToDifferences, cleanFromEmptiness;

  window.compareForms = function(form1, form2) {
    var differences, i1, i2, item_in_1, item_in_2, _i, _j, _len, _len1;
    form1 = $(form1).serializeArray();
    form2 = $(form2).serializeArray();
    differences = [];
    for (i1 = _i = 0, _len = form1.length; _i < _len; i1 = ++_i) {
      item_in_1 = form1[i1];
      for (i2 = _j = 0, _len1 = form2.length; _j < _len1; i2 = ++_j) {
        item_in_2 = form2[i2];
        if ((item_in_1 != null ? item_in_1.name : void 0) === (item_in_2 != null ? item_in_2.name : void 0)) {
          if (item_in_1.value !== item_in_2.value) {
            addToDifferences(item_in_2.name, item_in_1.value, item_in_2.value, differences);
          }
          delete form1[i1];
          delete form2[i2];
        }
      }
    }
    form1 = cleanFromEmptiness(form1);
    form2 = cleanFromEmptiness(form2);
    if (form1 != null) {
      form1.forEach(function(param) {
        return addToDifferences(param.name, null, null, differences, 'delete');
      });
    }
    if (form2 != null) {
      form2.forEach(function(param) {
        return addToDifferences(param.name, null, null, differences, 'insert');
      });
    }
    if (differences.length === 0) {
      return 'Формы идентичны';
    }
    return differences;
  };

  addToDifferences = function(paramName, oldValue, newValue, differences, type) {
    if (type == null) {
      type = 'update';
    }
    return differences.push(type === 'update' ? "Обновился парамметр '" + paramName + "': был '" + oldValue + "', а стал '" + newValue + "'" : type === 'delete' ? "Удалён парамметр '" + paramName + "'" : type === 'insert' ? "Добавлен новый парамметр: '" + paramName + "'" : void 0);
  };

  cleanFromEmptiness = function(array) {
    return array.filter(function(item) {
      return item;
    });
  };

}).call(this);
