// Generated by CoffeeScript 1.6.3
/*
  Функция расширения url с заданными парамметрами
*/


(function() {
  var http_build_query;

  window.extendUrlByParams = function(url, params) {
    var clearUrl, paramsFromUrl;
    paramsFromUrl = $.extend(window.parseQuery(url), params);
    clearUrl = url.split('?')[0];
    return clearUrl + '?' + http_build_query(paramsFromUrl);
  };

  http_build_query = function(data) {
    var arg_separator, i, key, tmp_arr, use_key, use_val;
    arg_separator = '&';
    tmp_arr = [];
    i = 0;
    for (key in data) {
      use_key = encodeURIComponent(key);
      use_val = encodeURIComponent(data[key].toString());
      use_val = use_val.replace(/%20/g, '+');
      if (!isNaN(key)) {
        use_key = numeric_prefix + i;
      }
      tmp_arr[i] = use_key + '=' + use_val;
      i++;
    }
    return tmp_arr.join(arg_separator);
  };

}).call(this);
